version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "meteor",
    "vue",
    "angular",
    "react",
    "ember",
    "angularjs"
  ]
  environment = [
    "nodejs",
    "mocha",
    "jquery",
    "vitest"
  ]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"